// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// breed
IntegerVector breed(IntegerVector Parents, int ns, int Ns, int nLoci);
RcppExport SEXP relSim_breed(SEXP ParentsSEXP, SEXP nsSEXP, SEXP NsSEXP, SEXP nLociSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type Parents(ParentsSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type Ns(NsSEXP);
    Rcpp::traits::input_parameter< int >::type nLoci(nLociSEXP);
    __result = Rcpp::wrap(breed(Parents, ns, Ns, nLoci));
    return __result;
END_RCPP
}
// calcFst
NumericVector calcFst(IntegerVector Pop, IntegerVector SubPopIdx, int N, int ns, int nLoci, IntegerVector NumLocusAlleles);
RcppExport SEXP relSim_calcFst(SEXP PopSEXP, SEXP SubPopIdxSEXP, SEXP NSEXP, SEXP nsSEXP, SEXP nLociSEXP, SEXP NumLocusAllelesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type Pop(PopSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type SubPopIdx(SubPopIdxSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nLoci(nLociSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NumLocusAlleles(NumLocusAllelesSEXP);
    __result = Rcpp::wrap(calcFst(Pop, SubPopIdx, N, ns, nLoci, NumLocusAlleles));
    return __result;
END_RCPP
}
// locusLRmix_Caller
double locusLRmix_Caller(IntegerVector ProfVic, IntegerVector ProfSus, NumericVector Freq);
RcppExport SEXP relSim_locusLRmix_Caller(SEXP ProfVicSEXP, SEXP ProfSusSEXP, SEXP FreqSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type ProfVic(ProfVicSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ProfSus(ProfSusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Freq(FreqSEXP);
    __result = Rcpp::wrap(locusLRmix_Caller(ProfVic, ProfSus, Freq));
    return __result;
END_RCPP
}
// LRmix
NumericVector LRmix(IntegerVector ProfVic, IntegerVector ProfSus, List listFreqs);
RcppExport SEXP relSim_LRmix(SEXP ProfVicSEXP, SEXP ProfSusSEXP, SEXP listFreqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type ProfVic(ProfVicSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ProfSus(ProfSusSEXP);
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    __result = Rcpp::wrap(LRmix(ProfVic, ProfSus, listFreqs));
    return __result;
END_RCPP
}
// locusIBS
IntegerVector locusIBS(IntegerVector ProfMat, int N);
RcppExport SEXP relSim_locusIBS(SEXP ProfMatSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type ProfMat(ProfMatSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    __result = Rcpp::wrap(locusIBS(ProfMat, N));
    return __result;
END_RCPP
}
// IBS_Caller
int IBS_Caller(IntegerVector Prof1, IntegerVector Prof2, int nLoci);
RcppExport SEXP relSim_IBS_Caller(SEXP Prof1SEXP, SEXP Prof2SEXP, SEXP nLociSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type Prof1(Prof1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Prof2(Prof2SEXP);
    Rcpp::traits::input_parameter< int >::type nLoci(nLociSEXP);
    __result = Rcpp::wrap(IBS_Caller(Prof1, Prof2, nLoci));
    return __result;
END_RCPP
}
// randomProfiles
IntegerVector randomProfiles(List listFreqs, int nBlockSize);
RcppExport SEXP relSim_randomProfiles(SEXP listFreqsSEXP, SEXP nBlockSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    Rcpp::traits::input_parameter< int >::type nBlockSize(nBlockSizeSEXP);
    __result = Rcpp::wrap(randomProfiles(listFreqs, nBlockSize));
    return __result;
END_RCPP
}
// randomSibs
IntegerVector randomSibs(IntegerVector ProfSib1, List listFreqs, int nBlockSize);
RcppExport SEXP relSim_randomSibs(SEXP ProfSib1SEXP, SEXP listFreqsSEXP, SEXP nBlockSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type ProfSib1(ProfSib1SEXP);
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    Rcpp::traits::input_parameter< int >::type nBlockSize(nBlockSizeSEXP);
    __result = Rcpp::wrap(randomSibs(ProfSib1, listFreqs, nBlockSize));
    return __result;
END_RCPP
}
// randomChildren
IntegerVector randomChildren(IntegerVector ProfParent, List listFreqs, int nBlockSize);
RcppExport SEXP relSim_randomChildren(SEXP ProfParentSEXP, SEXP listFreqsSEXP, SEXP nBlockSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type ProfParent(ProfParentSEXP);
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    Rcpp::traits::input_parameter< int >::type nBlockSize(nBlockSizeSEXP);
    __result = Rcpp::wrap(randomChildren(ProfParent, listFreqs, nBlockSize));
    return __result;
END_RCPP
}
// lrPC_Caller
double lrPC_Caller(IntegerVector ProfParent, IntegerVector ProfChild, List listFreqs);
RcppExport SEXP relSim_lrPC_Caller(SEXP ProfParentSEXP, SEXP ProfChildSEXP, SEXP listFreqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type ProfParent(ProfParentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ProfChild(ProfChildSEXP);
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    __result = Rcpp::wrap(lrPC_Caller(ProfParent, ProfChild, listFreqs));
    return __result;
END_RCPP
}
// maximizeLRPC
List maximizeLRPC(List listFreqs, int nBlockSize);
RcppExport SEXP relSim_maximizeLRPC(SEXP listFreqsSEXP, SEXP nBlockSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    Rcpp::traits::input_parameter< int >::type nBlockSize(nBlockSizeSEXP);
    __result = Rcpp::wrap(maximizeLRPC(listFreqs, nBlockSize));
    return __result;
END_RCPP
}
// lrSib_Caller
double lrSib_Caller(IntegerVector ProfSib1, IntegerVector ProfSib2, List listFreqs);
RcppExport SEXP relSim_lrSib_Caller(SEXP ProfSib1SEXP, SEXP ProfSib2SEXP, SEXP listFreqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type ProfSib1(ProfSib1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ProfSib2(ProfSib2SEXP);
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    __result = Rcpp::wrap(lrSib_Caller(ProfSib1, ProfSib2, listFreqs));
    return __result;
END_RCPP
}
// blockStatCounts
IntegerVector blockStatCounts(IntegerVector Prof1, IntegerVector Prof2, int nProf, List listFreqs, int nCode, bool bFalseNeg, IntegerVector IBSthresh, NumericVector LRthresh, int nNumResults);
RcppExport SEXP relSim_blockStatCounts(SEXP Prof1SEXP, SEXP Prof2SEXP, SEXP nProfSEXP, SEXP listFreqsSEXP, SEXP nCodeSEXP, SEXP bFalseNegSEXP, SEXP IBSthreshSEXP, SEXP LRthreshSEXP, SEXP nNumResultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type Prof1(Prof1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Prof2(Prof2SEXP);
    Rcpp::traits::input_parameter< int >::type nProf(nProfSEXP);
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    Rcpp::traits::input_parameter< int >::type nCode(nCodeSEXP);
    Rcpp::traits::input_parameter< bool >::type bFalseNeg(bFalseNegSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type IBSthresh(IBSthreshSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type LRthresh(LRthreshSEXP);
    Rcpp::traits::input_parameter< int >::type nNumResults(nNumResultsSEXP);
    __result = Rcpp::wrap(blockStatCounts(Prof1, Prof2, nProf, listFreqs, nCode, bFalseNeg, IBSthresh, LRthresh, nNumResults));
    return __result;
END_RCPP
}
// blockStats
List blockStats(IntegerVector Prof1, IntegerVector Prof2, int nProf, List listFreqs, int nCode);
RcppExport SEXP relSim_blockStats(SEXP Prof1SEXP, SEXP Prof2SEXP, SEXP nProfSEXP, SEXP listFreqsSEXP, SEXP nCodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type Prof1(Prof1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Prof2(Prof2SEXP);
    Rcpp::traits::input_parameter< int >::type nProf(nProfSEXP);
    Rcpp::traits::input_parameter< List >::type listFreqs(listFreqsSEXP);
    Rcpp::traits::input_parameter< int >::type nCode(nCodeSEXP);
    __result = Rcpp::wrap(blockStats(Prof1, Prof2, nProf, listFreqs, nCode));
    return __result;
END_RCPP
}
