# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.breed <- function(Parents, ns, Ns, nLoci) {
    .Call('relSim_breed', PACKAGE = 'relSim', Parents, ns, Ns, nLoci)
}

.calcFst <- function(Pop, SubPopIdx, N, ns, nLoci, NumLocusAlleles) {
    .Call('relSim_calcFst', PACKAGE = 'relSim', Pop, SubPopIdx, N, ns, nLoci, NumLocusAlleles)
}

locusLRmix_Caller <- function(ProfVic, ProfSus, Freq) {
    .Call('relSim_locusLRmix_Caller', PACKAGE = 'relSim', ProfVic, ProfSus, Freq)
}

LRmix_Caller <- function(ProfVic, ProfSus, listFreqs) {
    .Call('relSim_LRmix', PACKAGE = 'relSim', ProfVic, ProfSus, listFreqs)
}

locusIBS_Caller <- function(ProfMat, N) {
    .Call('relSim_locusIBS', PACKAGE = 'relSim', ProfMat, N)
}

IBS_Caller <- function(Prof1, Prof2, nLoci) {
    .Call('relSim_IBS_Caller', PACKAGE = 'relSim', Prof1, Prof2, nLoci)
}

randomProfiles <- function(listFreqs, nBlockSize = 1000L) {
    .Call('relSim_randomProfiles', PACKAGE = 'relSim', listFreqs, nBlockSize)
}

randomSibs <- function(ProfSib1, listFreqs, nBlockSize) {
    .Call('relSim_randomSibs', PACKAGE = 'relSim', ProfSib1, listFreqs, nBlockSize)
}

randomChildren <- function(ProfParent, listFreqs, nBlockSize) {
    .Call('relSim_randomChildren', PACKAGE = 'relSim', ProfParent, listFreqs, nBlockSize)
}

lrPC_Caller <- function(ProfParent, ProfChild, listFreqs) {
    .Call('relSim_lrPC_Caller', PACKAGE = 'relSim', ProfParent, ProfChild, listFreqs)
}

maximizeLRPC <- function(listFreqs, nBlockSize) {
    .Call('relSim_maximizeLRPC', PACKAGE = 'relSim', listFreqs, nBlockSize)
}

blockStatCounts <- function(Prof1, Prof2, nProf, listFreqs, nCode, bFalseNeg, IBSthresh, LRthresh, nNumResults) {
    .Call('relSim_blockStatCounts', PACKAGE = 'relSim', Prof1, Prof2, nProf, listFreqs, nCode, bFalseNeg, IBSthresh, LRthresh, nNumResults)
}

blockStats <- function(Prof1, Prof2, nProf, listFreqs, nCode) {
    .Call('relSim_blockStats', PACKAGE = 'relSim', Prof1, Prof2, nProf, listFreqs, nCode)
}

