# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('relSim_rcpp_hello_world', PACKAGE = 'relSim')
}

randomProfiles <- function(listFreqs, nBlockSize) {
    .Call('relSim_randomProfiles', PACKAGE = 'relSim', listFreqs, nBlockSize)
}

